### ISSUE TITLE
Improve

### ISSUE THREAD

**Issue by TobyEalden** [nqminds/nqm-app-minimal#3]
# material-ui
- upgrade to material-ui beta.2
- remove styleManager
- add 'withApp' to inject application styles into the context (see workbench)
- make sure all components use withApp (rather than withStyles)

# general upgrades
- upgrade React.PropTypes -> prop-types (npm)
- make resource creation use inline schema definition rather than schema id
- make sure createAndCreateFilter works

# new features
- add example pages
  - add a page that has a layout similar to nqm-app-framework, e.g. App Bar at top, Drawer component on left etc
  - add a page that uses a plain layout, e.g. just a header and content that flows
- include a link to the nqminds dashboard (as well as sign-out)

# application modes
- create an application for each mode supported mode, e.g. 
  - user owns data
  - app chooses who owns data
  - app is read-only
- create an example showing app-server logic
 - use the app server web session to make a request to the TDX on behalf of the current user

# documentation
- update the README

**Comment by iendjinn** [comment]
Assuming no one is currently using the v2 branch, is it safe for me to implement the upgrade to withApp even though it won't be working until after the upgrade to material ui 1.0?

**Comment by TobyEalden** [comment]
Might as well wait - I want it to have 'public' and 'authenticated' routes, which I'll copy from the careshare marketplace app, but I'm still tweaking it.

**Comment by iendjinn** [comment]
OK, just found this: https://medium.com/@mweststrate/how-to-safely-use-react-context-b7e343eff076

Which is linked from the react docs. It suggests that the usage of context to pass theme (or presumably a app wide style sheet) is perfectly legitimate, so long as we use a HoC to avoid lots of digging if they change the api :)
